//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="GuessingServiceInterface")]
public interface GuessingServiceInterface
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuessingServiceInterface/SecretNumber", ReplyAction="http://tempuri.org/GuessingServiceInterface/SecretNumberResponse")]
    int SecretNumber(int lower, int upper);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuessingServiceInterface/SecretNumber", ReplyAction="http://tempuri.org/GuessingServiceInterface/SecretNumberResponse")]
    System.Threading.Tasks.Task<int> SecretNumberAsync(int lower, int upper);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuessingServiceInterface/CheckNumber", ReplyAction="http://tempuri.org/GuessingServiceInterface/CheckNumberResponse")]
    string CheckNumber(int userNumber, int secretNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuessingServiceInterface/CheckNumber", ReplyAction="http://tempuri.org/GuessingServiceInterface/CheckNumberResponse")]
    System.Threading.Tasks.Task<string> CheckNumberAsync(int userNumber, int secretNumber);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface GuessingServiceInterfaceChannel : GuessingServiceInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GuessingServiceInterfaceClient : System.ServiceModel.ClientBase<GuessingServiceInterface>, GuessingServiceInterface
{
    
    public GuessingServiceInterfaceClient()
    {
    }
    
    public GuessingServiceInterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GuessingServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GuessingServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GuessingServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int SecretNumber(int lower, int upper)
    {
        return base.Channel.SecretNumber(lower, upper);
    }
    
    public System.Threading.Tasks.Task<int> SecretNumberAsync(int lower, int upper)
    {
        return base.Channel.SecretNumberAsync(lower, upper);
    }
    
    public string CheckNumber(int userNumber, int secretNumber)
    {
        return base.Channel.CheckNumber(userNumber, secretNumber);
    }
    
    public System.Threading.Tasks.Task<string> CheckNumberAsync(int userNumber, int secretNumber)
    {
        return base.Channel.CheckNumberAsync(userNumber, secretNumber);
    }
}
