//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessServiceConsoleApplication.PythagoreanService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalcPythagorean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CalcPythagorean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int calculationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double length1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double length2Field;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int calculationType {
            get {
                return this.calculationTypeField;
            }
            set {
                if ((this.calculationTypeField.Equals(value) != true)) {
                    this.calculationTypeField = value;
                    this.RaisePropertyChanged("calculationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double length1 {
            get {
                return this.length1Field;
            }
            set {
                if ((this.length1Field.Equals(value) != true)) {
                    this.length1Field = value;
                    this.RaisePropertyChanged("length1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double length2 {
            get {
                return this.length2Field;
            }
            set {
                if ((this.length2Field.Equals(value) != true)) {
                    this.length2Field = value;
                    this.RaisePropertyChanged("length2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PythagoreanService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcPythagorean", ReplyAction="http://tempuri.org/IService/CalcPythagoreanResponse")]
        AccessServiceConsoleApplication.PythagoreanService.CalcPythagoreanResponse CalcPythagorean(AccessServiceConsoleApplication.PythagoreanService.CalcPythagoreanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcPythagorean", ReplyAction="http://tempuri.org/IService/CalcPythagoreanResponse")]
        System.Threading.Tasks.Task<AccessServiceConsoleApplication.PythagoreanService.CalcPythagoreanResponse> CalcPythagoreanAsync(AccessServiceConsoleApplication.PythagoreanService.CalcPythagoreanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcPythagoreanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AccessServiceConsoleApplication.PythagoreanService.CalcPythagorean CalcPythagorean;
        
        public CalcPythagoreanRequest() {
        }
        
        public CalcPythagoreanRequest(AccessServiceConsoleApplication.PythagoreanService.CalcPythagorean CalcPythagorean) {
            this.CalcPythagorean = CalcPythagorean;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcPythagoreanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<double> @double;
        
        public CalcPythagoreanResponse() {
        }
        
        public CalcPythagoreanResponse(System.Nullable<double> @double) {
            this.@double = @double;
        }
    }
}
